---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/MRI1p8rot2/MRI1p8rot2.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14366/articles/278183/master/file/figures/MRI1p8rot2/MRI1p8rot2.svg"
