---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/convection_TCAN/convection_TCAN.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14366/articles/278183/master/file/figures/convection_TCAN/convection_TCAN.png"
    folder_url: "/users/14366/articles/278183/master/folder/figures/convection_TCAN"
