---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/SPB/SPB.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14366/articles/278183/master/file/figures/SPB/SPB.svg"
    folder_url: "/users/14366/articles/278183/master/folder/figures/SPB"
