---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/BHspin/BHspin.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14366/articles/278183/master/folder/figures/BHspin"
    url: "/users/14366/articles/278183/master/file/figures/BHspin/BHspin.png"
