---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Starling12/Starling.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14366/articles/278183/master/folder/figures/Starling12"
    url: "/users/14366/articles/278183/master/file/figures/Starling12/Starling.svg"
